export const tokens = {
  spacing: {
    blockPaddingX: 'px-4 md:px-6',
    blockPaddingY: 'py-4 md:py-6',
    blockGapY: 'space-y-4',
    blockRowGap: 'gap-4',
    gridGap: 'gap-4 lg:gap-6',
    fieldGapY: 'space-y-4',
    dashboardSectionGap: 'space-y-6',
    screenPadding: 'p-4 md:p-6',
    tight: 'space-y-1.5',
    widgetGap: 'gap-2',
    tinyGap: 'gap-1',
    elementPadding: 'px-3 py-2',
    containerPadding: 'p-3',
  },
  borders: {
    default: 'border border-[var(--border-subtle)]',
    input: 'border border-[rgba(0,0,0,0.15)] dark:border-[rgba(255,255,255,0.15)]',
    divider: 'border-t border-[var(--border-subtle)]',
  },
  radius: {
    card: 'rounded-xl',
    pill: 'rounded-full',
    input: 'rounded-lg',
    sm: 'rounded',
  },
  typography: {
    blockTitle: 'text-sm font-bold text-[var(--text)] uppercase tracking-wide',
    sectionLabel: 'text-[10px] sm:text-xs font-bold text-[var(--muted)] uppercase tracking-wider',
    navLink: 'text-xs font-bold text-[var(--muted)] hover:text-[var(--text)] uppercase tracking-wide transition-colors',
    body: 'text-sm text-[var(--text)] leading-relaxed',
    bodySemi: 'text-sm font-semibold text-[var(--text)] leading-relaxed',
    bodyLarge: 'text-base text-[var(--text)] leading-relaxed',
    bodyMuted: 'text-sm text-[var(--muted)] leading-relaxed',
    meta: 'text-xs text-[var(--muted)]',
    h1: 'text-2xl font-bold text-[var(--text)] tracking-tight',
    h2: 'text-xl font-semibold text-[var(--text)] tracking-tight',
    h3: 'text-lg font-medium text-[var(--text)] tracking-tight',
    statValue: 'text-sm sm:text-base font-semibold text-[var(--text)]',
  },
  icons: {
    sm: 'w-4 h-4',
    md: 'w-5 h-5',
    lg: 'w-6 h-6',
    xl: 'w-8 h-8',
  },
} as const;
